name: _
publish_to: none

environment:
  sdk: '^3.12.2'

workspace:
  - backends/global/top_attempt_global_client
  - backends/global/top_attempt_global_server
  - backends/local/top_attempt_local_client
  - backends/local/top_attempt_local_server
  - frontends/shared
  - frontends/top_attempt_enduser_flutter
  - frontends/top_attempt_global_flutter
  - frontends/top_attempt_local_flutter
  
dependency_overrides:
  flutter_secure_storage: ^10.0.0

